<Project Sdk="Microsoft.NET.Sdk">

  <!-- Authors: Tarokh Torabi & Mohammad Amin Jalalian -->
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CaseManagement.Domain\CaseManagement.Domain.csproj" />
    <ProjectReference Include="..\CaseManagement.Shared\CaseManagement.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.0" />
  </ItemGroup>

</Project>
